services:
  uniquelance.backend.accountapi:
    image: ${DOCKER_REGISTRY-}accountapi_unique:1.0
    container_name: Unique.Lance.AccountAPI
    depends_on:
      postgres_db_accountservice:
        condition: service_healthy
    build:
      context: ./Backend
      dockerfile: AccountService.API/Dockerfile
    environment:
      ACCOUNT_DATABASE: ${ACCOUNT_DATABASE}
    ports:
      - "8080:80"
    restart: unless-stopped

  postgres_db_accountservice:
    image: postgres:17.0-bookworm
    container_name: Unique.Lance.PostgreSQL.AccountService
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:80"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: Unique.Lance.PostgreSQL.PgAdmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_db_accountservice
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://localhost:80/misc/ping" ]
      interval: 10s
      timeout: 10s
      start_period: 160s
      retries: 3

  redis_cache:
    image: redis:7.4-bookworm
    container_name: Unique.Lance.Redis
    environment:
      - REDIS_PASSWORD=root
      - REDIS_USER=admin
      - REDIS_USER_PASSWORD=admin
    ports:
      - "6380:6379"
    volumes:
      - ./redis_cache:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "root", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  rabbitmq_broker:
    image: rabbitmq:3-management
    container_name: Unique.Lance.RabbitMQ
    hostname: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq_data:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  rabbitmq_broker: